"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Copy, FileText, Save } from "lucide-react";
import { Editor as TinyMCEEditor } from "@tinymce/tinymce-react";

type ArticleType = "global" | "crypto" | "commodity" | "business" | "geopolitical";
type ArticleStatus = "draft" | "review" | "published";
type AIProvider = "auto" | "openai" | "gemini";

const TYPE_OPTIONS: Array<{ label: string; value: ArticleType }> = [
  { label: "Global Market", value: "global" },
  { label: "Crypto Update", value: "crypto" },
  { label: "Commodity Update", value: "commodity" },
  { label: "Business Deal", value: "business" },
  { label: "Geopolitical Impact", value: "geopolitical" },
];

const TINYMCE_API_KEY =
  process.env.NEXT_PUBLIC_TINYMCE_API_KEY ||
  "cqjhaf886qrh4n1is5ihif9u3fv1yr9c17bme0ojdbvb3chw";

const TINYMCE_INIT = {
  height: 520,
  menubar: true,
  branding: false,
  promotion: false,
  plugins: [
    "advlist",
    "autolink",
    "lists",
    "link",
    "image",
    "charmap",
    "preview",
    "anchor",
    "searchreplace",
    "visualblocks",
    "code",
    "fullscreen",
    "insertdatetime",
    "media",
    "table",
    "help",
    "wordcount",
  ],
  toolbar:
    "undo redo | blocks fontfamily fontsize | bold italic underline forecolor backcolor | " +
    "alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | " +
    "link image table | removeformat code fullscreen",
  content_style:
    "body { font-family: Inter, Arial, sans-serif; font-size: 17px; line-height: 1.7; } p { margin: 0 0 1em; }",
};

export default function NewAdminArticlePage() {
  const { data: session, status } = useSession();
  const router = useRouter();

  const [title, setTitle] = useState("");
  const [type, setType] = useState<ArticleType>("global");
  const [content, setContent] = useState("");
  const [excerpt, setExcerpt] = useState("");
  const [tags, setTags] = useState("");
  const [image, setImage] = useState("");
  const [metaTitle, setMetaTitle] = useState("");
  const [metaDescription, setMetaDescription] = useState("");
  const [prompt, setPrompt] = useState("");
  const [promptLoading, setPromptLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [aiProvider, setAiProvider] = useState<AIProvider>("auto");
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState("");
  const [generateMessage, setGenerateMessage] = useState("");
  const [autoFillOnTitleBlur, setAutoFillOnTitleBlur] = useState(true);
  const [lastAutoGeneratedTitle, setLastAutoGeneratedTitle] = useState("");

  const canEdit =
    status === "authenticated" &&
    (session?.user?.role === "admin" || session?.user?.role === "editor");

  useEffect(() => {
    if (status === "loading") return;
    if (!canEdit) {
      router.push("/");
    }
  }, [status, canEdit, router]);

  useEffect(() => {
    let active = true;
    async function loadPrompt() {
      try {
        setPromptLoading(true);
        const res = await fetch(`/api/articles/prompts?type=${type}`, { cache: "no-store" });
        const payload = await res.json();
        if (!active) return;
        if (!res.ok || !payload.success) {
          setPrompt("");
          return;
        }
        setPrompt(payload.data?.prompt || "");
      } catch (err) {
        console.error("Failed to load prompt", err);
        if (active) {
          setPrompt("");
        }
      } finally {
        if (active) {
          setPromptLoading(false);
        }
      }
    }
    loadPrompt();
    return () => {
      active = false;
    };
  }, [type]);

  const parsedTags = useMemo(
    () =>
      tags
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean),
    [tags]
  );

  async function copyPrompt() {
    if (!prompt) return;
    try {
      await navigator.clipboard.writeText(prompt);
      setCopied(true);
      setTimeout(() => setCopied(false), 1200);
    } catch (err) {
      console.error("Clipboard copy failed", err);
    }
  }

  async function handleGenerateFromTitle(manual = true) {
    const trimmedTitle = title.trim();
    if (!trimmedTitle) {
      if (manual) {
        setGenerateError("Please enter title first.");
      }
      return;
    }

    try {
      setGenerateError("");
      setGenerateMessage("");
      setGenerating(true);

      const res = await fetch("/api/articles/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: trimmedTitle,
          type,
          provider: aiProvider,
        }),
      });

      const payload = await res.json();
      if (!res.ok || !payload.success) {
        throw new Error(payload.error || "Failed to generate article");
      }

      const generated = payload.data || {};

      if (typeof generated.title === "string" && generated.title.trim()) {
        setTitle(generated.title.trim());
      }
      if (typeof generated.excerpt === "string") {
        setExcerpt(generated.excerpt);
      }
      if (typeof generated.content === "string") {
        setContent(generated.content);
      }
      if (Array.isArray(generated.tags)) {
        setTags(
          generated.tags
            .filter((item: unknown): item is string => typeof item === "string")
            .join(", ")
        );
      }
      if (generated.seo && typeof generated.seo === "object") {
        const seo = generated.seo as {
          metaTitle?: string;
          metaDescription?: string;
        };
        if (typeof seo.metaTitle === "string") {
          setMetaTitle(seo.metaTitle);
        }
        if (typeof seo.metaDescription === "string") {
          setMetaDescription(seo.metaDescription);
        }
      }
      if (typeof generated.image === "string" && generated.image.trim()) {
        setImage(generated.image.trim());
      }

      const providerUsed = typeof generated.provider === "string" ? generated.provider : aiProvider;
      const imageSource =
        typeof generated.imageSource === "string" && generated.imageSource
          ? generated.imageSource
          : "fallback";
      setGenerateMessage(
        `Generated using ${providerUsed.toUpperCase()} with image source: ${imageSource}.`
      );
      setLastAutoGeneratedTitle(trimmedTitle);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to generate article";
      if (manual || !content.trim()) {
        setGenerateError(message);
      }
    } finally {
      setGenerating(false);
    }
  }

  function handleTitleBlur() {
    const trimmedTitle = title.trim();
    if (!autoFillOnTitleBlur) return;
    if (!trimmedTitle) return;
    if (generating) return;
    if (content.trim()) return;
    if (trimmedTitle === lastAutoGeneratedTitle) return;
    void handleGenerateFromTitle(false);
  }

  async function handleSubmit(targetStatus: ArticleStatus, e?: FormEvent) {
    if (e) e.preventDefault();

    try {
      setError("");
      setSubmitting(true);
      const res = await fetch("/api/articles", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title,
          type,
          content,
          excerpt,
          image,
          tags: parsedTags,
          status: targetStatus,
          aiGenerated: true,
          seo: {
            metaTitle,
            metaDescription,
            keywords: parsedTags,
          },
        }),
      });
      const payload = await res.json();
      if (!res.ok || !payload.success) {
        throw new Error(payload.error || "Failed to create article");
      }
      const id = payload?.data?._id;
      if (id) {
        router.push(`/admin/articles/${id}`);
      } else {
        router.push("/admin/articles");
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to create article";
      setError(message);
    } finally {
      setSubmitting(false);
    }
  }

  if (status === "loading") {
    return <div className="w-full p-8 text-slate-600">Loading...</div>;
  }

  return (
    <div className="w-full space-y-6 p-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-slate-900">Create AI Article</h1>
          <p className="mt-1 text-slate-600">Start as Draft, then move to Review and Publish.</p>
        </div>
        <Link
          href="/admin/articles"
          className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
        >
          Back to Articles
        </Link>
      </div>

      {error ? (
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </div>
      ) : null}

      <div className="grid gap-6 lg:grid-cols-[1.25fr_0.75fr]">
        <form
          className="space-y-4 rounded-xl border border-slate-200 bg-white p-5"
          onSubmit={(e) => handleSubmit("draft", e)}
        >
          <div className="grid gap-4 md:grid-cols-2">
            <div className="md:col-span-2">
              <label className="mb-1 block text-sm font-medium text-slate-700">Title</label>
              <input
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                onBlur={handleTitleBlur}
                placeholder="Headline"
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-slate-400 focus:outline-none"
                required
              />
            </div>

            <div className="md:col-span-2 rounded-lg border border-slate-200 bg-slate-50 p-3">
              <div className="flex flex-wrap items-end gap-3">
                <div>
                  <label className="mb-1 block text-xs font-medium text-slate-700">AI Provider</label>
                  <select
                    value={aiProvider}
                    onChange={(e) => setAiProvider(e.target.value as AIProvider)}
                    className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm focus:border-slate-400 focus:outline-none"
                  >
                    <option value="auto">Auto (ChatGPT then Gemini)</option>
                    <option value="openai">ChatGPT</option>
                    <option value="gemini">Gemini</option>
                  </select>
                </div>

                <label className="mb-1 inline-flex items-center gap-2 text-sm text-slate-700">
                  <input
                    type="checkbox"
                    checked={autoFillOnTitleBlur}
                    onChange={(e) => setAutoFillOnTitleBlur(e.target.checked)}
                    className="rounded border-slate-300"
                  />
                  Auto-fill on title blur
                </label>

                <button
                  type="button"
                  disabled={generating || !title.trim()}
                  onClick={() => {
                    void handleGenerateFromTitle(true);
                  }}
                  className="rounded-lg border border-indigo-300 bg-indigo-50 px-3 py-2 text-sm font-medium text-indigo-800 hover:bg-indigo-100 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  {generating ? "Generating..." : "Generate from Title"}
                </button>
              </div>
              {generateError ? (
                <p className="mt-2 text-xs text-red-600">{generateError}</p>
              ) : null}
              {generateMessage ? (
                <p className="mt-2 text-xs text-green-700">{generateMessage}</p>
              ) : null}
            </div>

            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Type</label>
              <select
                value={type}
                onChange={(e) => setType(e.target.value as ArticleType)}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-slate-400 focus:outline-none"
              >
                {TYPE_OPTIONS.map((item) => (
                  <option key={item.value} value={item.value}>
                    {item.label}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Cover Image URL</label>
              <input
                value={image}
                onChange={(e) => setImage(e.target.value)}
                placeholder="https://..."
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-slate-400 focus:outline-none"
              />
            </div>

            <div className="md:col-span-2">
              <label className="mb-1 block text-sm font-medium text-slate-700">
                Excerpt (optional)
              </label>
              <textarea
                value={excerpt}
                onChange={(e) => setExcerpt(e.target.value)}
                rows={3}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-slate-400 focus:outline-none"
              />
            </div>

            <div className="md:col-span-2">
              <label className="mb-1 block text-sm font-medium text-slate-700">
                Content (Google-doc style editor)
              </label>
              <div className="overflow-hidden rounded-lg border border-slate-300">
                <TinyMCEEditor
                  apiKey={TINYMCE_API_KEY}
                  value={content}
                  onEditorChange={(value) => setContent(value)}
                  init={TINYMCE_INIT}
                />
              </div>
            </div>

            <div className="md:col-span-2">
              <label className="mb-1 block text-sm font-medium text-slate-700">
                Tags (comma separated)
              </label>
              <input
                value={tags}
                onChange={(e) => setTags(e.target.value)}
                placeholder="markets, fed, oil, earnings"
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-slate-400 focus:outline-none"
              />
            </div>

            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">SEO Meta Title</label>
              <input
                value={metaTitle}
                onChange={(e) => setMetaTitle(e.target.value)}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-slate-400 focus:outline-none"
              />
            </div>

            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">
                SEO Meta Description
              </label>
              <input
                value={metaDescription}
                onChange={(e) => setMetaDescription(e.target.value)}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-slate-400 focus:outline-none"
              />
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2 border-t border-slate-100 pt-3">
            <button
              type="submit"
              disabled={submitting}
              className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-60"
            >
              <Save size={16} />
              Save Draft
            </button>
            <button
              type="button"
              disabled={submitting}
              onClick={() => handleSubmit("review")}
              className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-sm font-medium text-amber-800 hover:bg-amber-100 disabled:opacity-60"
            >
              Create in Review
            </button>
            <button
              type="button"
              disabled={submitting}
              onClick={() => handleSubmit("published")}
              className="rounded-lg border border-green-300 bg-green-50 px-3 py-2 text-sm font-medium text-green-800 hover:bg-green-100 disabled:opacity-60"
            >
              Publish Directly
            </button>
          </div>
        </form>

        <aside className="space-y-4 rounded-xl border border-slate-200 bg-white p-5">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-slate-900">Gemini Prompt</h2>
            <button
              type="button"
              onClick={copyPrompt}
              className="inline-flex items-center gap-1 rounded-md border border-slate-300 px-2.5 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
            >
              <Copy size={14} />
              {copied ? "Copied" : "Copy"}
            </button>
          </div>
          <p className="text-xs text-slate-500">
            This template is used by auto-generation and can still be copied for manual use.
          </p>
          <div className="max-h-[520px] overflow-auto rounded-lg border border-slate-200 bg-slate-50 p-3">
            {promptLoading ? (
              <p className="text-sm text-slate-500">Loading prompt...</p>
            ) : (
              <pre className="whitespace-pre-wrap text-xs leading-5 text-slate-700">{prompt}</pre>
            )}
          </div>
          <button
            type="button"
            onClick={() => {
              if (!content.trim() && prompt.trim()) {
                setContent(`<h1>${title || "Title"}</h1>\n<p>${prompt}</p>`);
              }
            }}
            className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
          >
            <FileText size={16} />
            Insert Template to Content
          </button>
        </aside>
      </div>
    </div>
  );
}
